#!/usr/bin/env bash

# Organization: Grey-box
# Project: Cybercafe
# File: Cybercafe_orchestrator.sh
# Description: One-command lifecycle runner for Cybercafe.
# Wraps cybercafe CLI: build → run → status → shutdown
# Target: T95 device via Termux (root required)
# Usage: bash Cybercafe_orchestrator.sh [--rebuild] [COMMAND]

# Prerequisites: 
#   - ADB connected to T95 (adb connect <device-ip>:5555)
#   - Termux installed on T95 with bash, make, sqlite3
#   - Root access confirmed (whoami returns 'root')
#   - cybercafe.conf present in the same directory as this script
#   - preflight_t95.sh passed before running this script

# Commands:
#   all       Full lifecycle: preflight → build → run → status (default)
#   build     Compile cybercafe.sh into the runnable cybercafe binary
#   start     Start the Cybercafe infrastructure (daemon + hotspot check)
#   status    Print current running state of the Cybercafe daemon
#   shutdown  Send graceful shutdown signal and wait for clean stop
#
# Flags:
#   --rebuild   Force a fresh build even if the binary already exists
#
# Examples:
#   bash cybercafe_orchestrator.sh               # runs full lifecycle
#   bash cybercafe_orchestrator.sh build         # build only
#   bash cybercafe_orchestrator.sh start         # start only
#   bash cybercafe_orchestrator.sh --rebuild all # force rebuild then full run
#   bash cybercafe_orchestrator.sh shutdown      # graceful shutdown
#
# Logs:
#   All output is written to orchestrator.log in the same directory.
#   For Cybercafe-specific errors, see error.log (generated by cybercafe.sh).
#
# Recovery:
#   If the T95 loses network access during a run:
#   1. Reboot the T95
#   2. Reconnect ADB: adb connect <device-ip>:5555
#   3. Run: bash Backend/test/integration/restore_t95_baseline.sh
#   4. Re-run: bash Backend/test/integration/preflight_t95.sh

# Exit immediately if any command fails, treat unset variables as errors,
# and propagate errors through pipes. This prevents silent failures
# from cascading into later stages.
set -euo pipefail

# Resolving the absolute path of the directory this scripts lives.
# Ensures all file references work regardless of where script is called from.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
UTIL_PATH="/data/data/com.termux/files/usr/bin"

# Path to the compiled cybercafe binary produced by 'make all'.
# Main CLI (Command Line Interface) all lifecycle commands are routed through.
BINARY="$SCRIPT_DIR/cybercafe"

# Path to the cybercafe config. file
# Environmental variables contained (HS_INTERFACE and DATABASE_PATH) 
# required by the backend scripts and must exist before running.
CONF="$SCRIPT_DIR/cybercafe.conf"

# Path to the log file where every stage logs automatically.
# Use for Validation evidence and debugging.
LOG="$SCRIPT_DIR/orchestrator.log"

# These functions standardize output format across all stages.
# All messages are timestamped and written to both terminal and log file.

# INFO — normal progress messages
log()   { echo "[$(date '+%H:%M:%S')] [INFO]  $*" | tee -a "$LOG"; }

# WARN — non-fatal issues that should be noted but won't stop execution
warn()  { echo "[$(date '+%H:%M:%S')] [WARN]  $*" | tee -a "$LOG"; }

# ERROR — fatal issues that immediately halt the script with exit code 1
error() { echo "[$(date '+%H:%M:%S')] [ERROR] $*" | tee -a "$LOG" >&2; exit 1; }

# Preflight validates the environment before any lifecycle stage runs.
# Acted as a safety gate. If anything here fails, the system is not in state for
# orchestrator running safely.

# Checks performed:
#   - cybercafe.conf exists (required by cybercafe.sh at runtime)
#   - make is available (required for the build stage)
#   - sqlite3 is available (required for user/session operations)
#   - bash is available (required to execute all lifecycle scripts)
#
# If any check fails, the script exits with an error before
# any changes are made to the device.
preflight() {
    log "Running preflight checks..."

    # Verify config file exists. Needed at startup for cybercafe.sh and will fail silently without it
    [[ -f "$CONF" ]]   || error "cybercafe.conf not found in $SCRIPT_DIR"

    # Confirm make is available — needed to compile cybercafe.sh into binary
    command -v make || command -v "$UTIL_PATH/make" &>/dev/null || error "make is not installed"

    # Confirm sqlite3 is available — needed for list/user operations
    command -v sqlite3 || command -v "$UTIL_PATH/sqlite3" &>/dev/null || error "sqlite3 is not installed"

    # Confirm bash is available — all scripts in the project require bash
    command -v bash || command -v "$UTIL_PATH/bash"  &>/dev/null || error "bash is not installed"

    log "Preflight passed."
}

# Build runs 'make all' to compile cybercafe.sh into the executable binary.
# What does make all do (from Makefile):
#   cp cybercafe.sh cybercafe   - copies the script
#   chmod +x cybercafe          - makes it executable

# Idemopotent: skips the build if binary already exists and --rebuild was not passed.
# Preventing unnecessary rebuilds on repeated runs of orchestrator. 
run_build() {
    log "Stage: BUILD"
    cd "$SCRIPT_DIR"

    # Check if binary already exists and --rebuild was not requested.
    # Makefile only copies and chmods. Skipping an existing build is safe and
    # no compilation that could go stale.
    if [[ -x "$BINARY" ]] && [[ "${REBUILD:-false}" != "true" ]]; then
        warn "Binary already exists at $BINARY. Use --rebuild to force a fresh build."
    else
        # Run Makefile build target producing the cybercafe binary
        "$UTIL_PATH/make" all || error "make all failed - check Makefile in $SCRIPT_DIR"
        log "Build complete. Binary ready at $BINARY"
    fi
}

# Run/Start will start the infrastructure by calling 'cybercafe run'.
# What 'cybercafe run' does internally:
#   - Checks if the daemon is already running (idempotent guard)
#   - Starts Cybercafe_daemon.sh as a background nohup process
#   - Warns if the hotspot interface (HS_INTERFACE) is not up

# cybercafe.sh already guards against duplicate starts
# via a ps check, calling this stage twice is safe.
run_start() {
    log "Stage: RUN"
    "$BINARY" run || error "cybercafe run failed. Check error.log for details."
    log "Infrastructure start command issued."
}

# Status checks the current state of the Cybercafe daemon and hotspot.
# What 'cybercafe status' returns:
#   - Timestamp
#   - Status: Running / Stopped
#   - Process info (user, PID, start time) if running
#   - Hotspot interface details (ip add show dev $HS_INTERFACE)

# This stage also acts as a post-start validation:
# if the daemon is not running after 'run', it logs a warning
# so the operator knows to investigate before proceeding.
run_status() {
    log "Stage: STATUS"

    # Capture full status output. Write to the terminal and log file
    STATUS_OUTPUT=$("$BINARY" status 2>&1) || true
    echo "$STATUS_OUTPUT" | tee -a "$LOG"

    # Check for the expected "Status: Running" string.
    # If missing, warn — don't hard error, as the daemon may take
    # a moment to fully start on the T95.
    if echo "$STATUS_OUTPUT" | grep -q "Status: Running"; then
        log "Confirmed: Cybercafe daemon is running."
    else
        warn "Daemon may not be running yet — review status output above."
    fi

     --- Full Functionality Checks ---
    # Query all core data models and log their current state.
    # These run regardless of daemon status so we always capture
    # what is in the database at time of test. Failures are warnings
    # only — they do not halt the lifecycle.
 
    log "--- Listing Sessions ---"
    "$BINARY" list sessions 2>&1 | tee -a "$LOG" || warn "list sessions failed"
 
    log "--- Listing Users ---"
    "$BINARY" list users 2>&1 | tee -a "$LOG" || warn "list users failed"
 
    log "--- Listing Lanes ---"
    "$BINARY" list lanes 2>&1 | tee -a "$LOG" || warn "list lanes failed"
 
    log "--- Listing Rules ---"
    "$BINARY" list rules 2>&1 | tee -a "$LOG" || warn "list rules failed"
 
    log "Full functionality check complete. Review orchestrator.log for details."
}

# Shutdown sends graceful shutdown signal to the daemon.
# What 'cybercafe shutdown' does internally:
#   - Creates a 'shutdown.confirmed' lockfile as the stop signal
#   - Polls every second until the daemon process exits
#   - Removes the lockfile once the daemon has stopped cleanly

# Using || true here because if the daemon is already stopped,
# cybercafe shutdown exits non-zero — that is not a failure
# state for the orchestrator.
run_shutdown() {
    log "Stage: SHUTDOWN"
    "$BINARY" shutdown || true
    log "Shutdown signal sent. Daemon has stopped."
}

# Full Lifecycle
# Runs all stages in sequence as a single command.
# Primary deliverable. One command to execute full Cybercafe lifecycle on T95.
# Order:
#   1. preflight  — validate environment is ready
#   2. build      — compile cybercafe binary via make
#   3. start      — launch daemon + hotspot
#   4. status     — confirm running state

# Note: shutdown is intentionally not included in 'all'.
# The system is meant to stay running after 'all' completes.
# Call shutdown explicitly when you want to stop the system.
run_all() {
    preflight
    run_build
    run_start
    run_status
    
    log "Cybercafe is running."
    log "To stop: /data/data/com.termux/files/usr/bin/bash cybercafe_orchestrator.sh shutdown"
    log "Logs:    $LOG"
}

# Flag Parsing 
# Separates flags (--rebuild) from positional arguments (commands).
# This allows flags to be passed in any position, e.g.:
#   bash cybercafe_orchestrator.sh --rebuild all
#   bash cybercafe_orchestrator.sh all --rebuild  (also valid)

REBUILD=false
POSITIONAL=()
for arg in "$@"; do
    case $arg in
        --rebuild) REBUILD=true ;;          # set rebuild flag
        *)         POSITIONAL+=("$arg") ;;  # collect all other args
    esac
done

# Re-set positional parameters to the non-flag arguments
set -- "${POSITIONAL[@]:-}"

# Usage prints when an unrecognized command is passed or help is requested.
usage() {
    echo ""
    echo "Usage: bash cybercafe_orchestrator.sh [--rebuild] [COMMAND]"
    echo ""
    echo "Commands:"
    echo "  all       Full lifecycle: preflight → build → run → status (default)"
    echo "  build     Compile cybercafe.sh into the runnable cybercafe binary"
    echo "  start     Start the Cybercafe infrastructure"
    echo "  status    Show current running status of the daemon"
    echo "  shutdown  Send graceful shutdown signal and wait for clean stop"
    echo ""
    echo "Flags:"
    echo "  --rebuild   Force a fresh build even if the binary already exists"
    echo ""
    echo "Examples:"
    echo "  bash cybercafe_orchestrator.sh               # full lifecycle"
    echo "  bash cybercafe_orchestrator.sh build         # build only"
    echo "  bash cybercafe_orchestrator.sh --rebuild all # force rebuild + run"
    echo "  bash cybercafe_orchestrator.sh shutdown      # graceful stop"
    echo ""
    exit 1
}

# Main Entry Point
# Routes the command argument to the desired stage function. 
# Defaults to 'all' if no command is provided, so it can run the full lifecycle as expected
case "${1:-all}" in
    all)               run_all ;;
    build)             preflight && run_build ;;
    start)             preflight && run_start ;;
    status)            run_status ;;
    shutdown)          run_shutdown ;;
    help|--help|-h)    usage ;;
    *)  echo "Unknown command: ${1:-}"; usage ;;
esac
